POST 127.0.0.1:8000/appointment/
Content-Type: application/json


{
  "stylist_service": 2,
  "customer_name": "ابوالفضل میرزایی",
  "customer_number": "09123456789",
  "date": "2026-07-28",
  "time": "14:00"
}

###

POST 127.0.0.1:8000/payment/start/
Content-Type: application/json

{
  "appointment": 6
}
