# get available slots








# create an appointment
POST 127.0.0.1:8000/appointment/
Content-Type: application/json


{
  "stylist_service": 2,
  "customer_name": "ابوالفضل میرزایی",
  "customer_number": "09123456789",
  "date": "2026-08-1",
  "time": "14:00"
}

###
# statrt paying a appointment by send its id and get the payment url
POST 127.0.0.1:8000/payment/start/
Content-Type: application/json

{
  "appointment": 6
}


###
# secend step of paying and get the gateway callback
GET  127.0.0.1:8000/payment/callback/?Authority=123&Status=OK

###
# get stylist appointments by sending date
GET 127.0.0.1:8000/stylist/pari/appointments/?date=2026-08-01

###
# get an special appointment by id
GET 127.0.0.1:8000/appointment/8/

###

# update an appointment status by id

PATCH 127.0.0.1:8000/appointment/8/status/
Content-Type: application/json

{
  "status": "no_show"
}



###
# set day off for stylist

POST 127.0.0.1:8000/stylist/pari/day-off/
Content-Type: application/json

{
  "date": "2026-08-04",
  "reason": "مسافرت"
}

