# get available slots
GET 127.0.0.1:8000/slots/?stylist_service=2&date=2026-08-10



###
# create an appointment
POST 127.0.0.1:8000/appointment/create/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg4MTE5ODY5LCJpYXQiOjE3ODgxMTk1NjksImp0aSI6ImIwODdjYjU2YmJhNjQwMzA4Y2FjN2I2MmQ1MzExZjhkIiwidXNlcl9pZCI6IjEifQ.mwtF1ogo3YI1tIlnLuzKzk5JKT85ltcIvqvLFR56ze4

{
  "stylist_service": 3,
  "customer_name": "ابوالفضل ",
  "customer_number": "09123456789",
  "date": "2026-09-1",
  "time": "9:30"
}

###
# statrt paying a appointment by send its id and get the payment url
POST 127.0.0.1:8000/payment/start/
Content-Type: application/json

{
  "appointment": 14
}


###
# secend step of paying and get the gateway callback
GET  127.0.0.1:8000/payment/callback/?Authority=123&Status=OK

###
# get stylist appointments by sending date
GET 127.0.0.1:8000/stylist/pari/appointments/?date=2026-08-10

###
# get an special appointment by id
GET 127.0.0.1:8000/appointment/4/

###

# update an appointment status by id

PATCH 127.0.0.1:8000/appointment/8/status/
Content-Type: application/json

{
  "status": "no_shw"
}



###
# set day off for stylist

POST 127.0.0.1:8000/stylist/pari/day-off/
Content-Type: application/json

{
  "date": "2026-08-10",
  "reason": "مسافرت"
}
###


# request otp for login or register
POST 127.0.0.1:8000/api/auth/request-otp/
Content-Type: application/json

{
  "phone_number": "09131111112"
}

###


# verify otp
POST 127.0.0.1:8000/api/auth/verify-otp/
Content-Type: application/json

{
    "phone_number": "0913111111",
   "code": "878027"
}
###
# cancel a appointment by customer

POST 127.0.0.1:8000/appointment/cancel/1/
Authorization:



###

POST 127.0.0.1:8000/api/token/
Content-Type: application/json

{
  "username": "111",
  "password": "111"

}