# Generated by Django 5.2.15 on 2026-07-06 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام سالن به فارسی')),
                ('name_en', models.CharField(max_length=100, verbose_name='نام سالن به انگلیسی')),
                ('category', models.CharField(choices=[('mens_salon', 'آرایشگاه مردانه'), ('womens_salon', 'آرایشگاه زنانه')], max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=10)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
