# Generated by Django 5.2.15 on 2026-07-10 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("salon", "0004_dayoff_workinghours"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workinghours",
            options={"verbose_name": "ساعت کاری", "verbose_name_plural": "ساعات کاری"},
        ),
    ]
