# Generated by Django 5.2.15 on 2026-08-05 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_alter_workinghours_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoff',
            name='stylist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_offs', to='salon.stylist'),
        ),
    ]
