# Generated by Django 5.2.15 on 2026-08-25 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0007_stylist_user_alter_salon_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='salon',
        ),
    ]
