# Generated by Django 5.2.15 on 2026-08-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpgenerator',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
