# Generated by Django 5.2.15 on 2026-07-10 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salon', '0005_alter_workinghours_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=11)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending_payment', 'در انتظار پرداخت'), ('confirmed', 'تایید شده'), ('cancelled_by_customer', 'لغو شده توسط مشتری'), ('cancelled_by_stylist', 'لغو شده توسظ ارایشگر'), ('completed', 'انجام شده'), ('no_show', 'عدم حضور مشتری')], default='pending_payment', max_length=30)),
                ('service_price_snapshot', models.PositiveIntegerField()),
                ('deposit_amount', models.PositiveIntegerField()),
                ('platform_share', models.PositiveIntegerField()),
                ('salon_share', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stylist_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='salon.stylistservice')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت ها',
            },
        ),
    ]
