# Generated by Django 5.2.15 on 2026-07-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0003_payment_smslog"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
