# Generated by Django 5.2.15 on 2026-07-27 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0004_payment_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
