name: CI

on:
  push:
    branches:
      - main
      - master
      - recovery-branch

  pull_request:
    branches:
      - main
      - master
      - recovery-branch

jobs:
  test:

    runs-on: ubuntu-latest

    services:

      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: reservation_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

        ports:
          - 5432:5432

        options: >-
          --health-cmd "pg_isready -U postgres -d reservation_test"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5


      redis:
        image: redis:7-alpine

        ports:
          - 6379:6379

        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5


      rabbitmq:
        image: rabbitmq:4

        env:
          RABBITMQ_DEFAULT_USER: rabbit
          RABBITMQ_DEFAULT_PASS: rabbitpassword

        ports:
          - 5672:5672

        options: >-
          --health-cmd "rabbitmq-diagnostics -q ping"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5


    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Run migrations
        env:
          SECRET_KEY: django-insecure-ci-secret-key
          DEBUG: "True"
          ALLOWED_HOSTS: localhost,127.0.0.1

          POSTGRES_DB: reservation_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432

          CELERY_BROKER_URL: amqp://rabbit:rabbitpassword@localhost:5672//
          CELERY_RESULT_BACKEND: redis://localhost:6379/1

        run: |
          python manage.py migrate


      - name: Run tests
        env:
          SECRET_KEY: django-insecure-ci-secret-key
          DEBUG: "True"
          ALLOWED_HOSTS: localhost,127.0.0.1

          POSTGRES_DB: reservation_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432

          CELERY_BROKER_URL: amqp://rabbit:rabbitpassword@localhost:5672//
          CELERY_RESULT_BACKEND: redis://localhost:6379/1

        run: |
          python manage.py test